In [1]:
import numpy as np

# Numpy Arrays

## Numpy Arrays part one

In [2]:
# In numpy we have list and arrays
my_list = [1,2,3]
type(my_list)

list

In [3]:
# We can create an array from a list
arr = np.array(my_list)
type(arr)

numpy.ndarray

In [8]:
# If we transform a nested list into an array we'll have a matrix
my_list_nested = [[1,2,3], [4,5,6], [7,8,9]]
matrix = np.array(my_list_nested)
print(my_list_nested)
print(matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
matrix.shape

(3, 3)

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((3,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [22]:
np.ones(4) * 100

array([100., 100., 100., 100.])

In [26]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
# To create an identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Part Two

In [50]:
# Create random arrays with uniform (all values have the same probabilty) distribution
np.random.rand(3,3)

array([[0.15601864, 0.15599452, 0.05808361],
       [0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264]])

In [32]:
# We can do the same with a normal distribution
np.random.randn(5,5)

array([[ 0.61735487, -1.21236543,  0.01882842, -0.89937507, -0.90828402],
       [ 2.20562981,  2.01077352,  2.70373404, -1.34150472,  0.20058857],
       [-2.63186846, -0.84617164, -1.3122513 , -0.15373425, -0.9655139 ],
       [-0.33809325, -0.32686054,  0.42637734,  2.0514874 ,  0.00549408],
       [ 0.93526715, -1.39263975, -0.34437091,  0.81691655,  0.97620173]])

In [33]:
# Generate aleatory integer numbers
np.random.randint(0,100,45)

array([77, 52, 18, 95, 95, 58, 45, 89, 38,  8, 20, 82,  1, 40, 22, 40, 16,
       72, 60, 48, 51, 28, 21, 67, 20, 97,  7, 73, 74, 53,  4, 34, 12, 47,
        3, 66, 46, 41, 88, 93, 66, 12, 61, 67, 23])

In [49]:
# If we want reproduceble results we have to fix the seed
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [52]:
# The see setup must be in the same cell than the generator
np.random.rand(4)

array([0.52475643, 0.43194502, 0.29122914, 0.61185289])

In [53]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [55]:
rnarr = np.random.randint(0,50,10)
rnarr

array([27, 15, 14, 46, 43,  2, 36,  6, 20,  8])

In [56]:
arr.shape

(25,)

In [59]:
# Reshapes am array into another shape (size must be equal)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
# Obtain max value
rnarr.max()

46

In [64]:
# Obtain minimum value
rnarr.min()

2

In [65]:
# We can also obtain the index location for max and min values
print(rnarr.argmax())
print(rnarr.argmin())

3
5


In [67]:
print(rnarr[3])
print(rnarr[5])

46
2


In [70]:
# What are the types of the array's elements
rnarr.dtype

dtype('int32')

# Numpy indexing and selection

In [83]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
# Return an indiviadual element by position
arr[3]

3

In [74]:
# Return a range of elements startin at beging and no including the final position
arr[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [75]:
# If we omitte the begin or final position
print(arr[5:])
print(arr[:5])

[ 5  6  7  8  9 10]
[0 1 2 3 4]


In [84]:
# Be careful an slice of an array point to the original array
arr2 = arr.copy()
print(arr2)
slice_arr2 = arr2[0:5]
slice_arr2[:] = 23
print(slice_arr2)
print(arr2)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[23 23 23 23 23]
[23 23 23 23 23  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [85]:
# Indexing a 2d array
arr_2d  = np.array([[5,89,123],[9,10,34],[23,556,12]])
arr_2d

array([[  5,  89, 123],
       [  9,  10,  34],
       [ 23, 556,  12]])

In [87]:
# First column
arr_2d[:,0]

array([ 5,  9, 23])

In [89]:
# Last row
arr_2d[-1,:]

array([ 23, 556,  12])

In [90]:
# Middle elment
arr_2d[1,1]

10

In [94]:
# Last two elementes of the second row
arr_2d[1, -2:]

array([10, 34])

In [95]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
# Conditional selection
arr > 2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [97]:
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Numpy operations

In [98]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [100]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [101]:
arr * 100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [102]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [103]:
# We can do the same thing with arrays of the same shape
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [104]:
# Be aware that divide by zero produces a warning rather than error
1 / arr

<ipython-input-104-ea5d6dddc9a3>:2: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [105]:
arr / arr

<ipython-input-105-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [106]:
# We can use universal array functions
print(np.sqrt(arr))
print(np.log(arr))
print(np.sin(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


<ipython-input-106-27a3f4f3b40c>:3: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))


In [108]:
# Some statiscals
print("sum",arr.sum())
print("mean", arr.mean())
print("standard deviation", arr.std())

sum 45
mean 4.5
standard deviation 2.8722813232690143


In [109]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [111]:
arr_2d.shape

(3, 4)

In [113]:
# Sum without parameters sums all elementes in the matrix
arr_2d.sum()

78

In [115]:
# We can sum in an axis 0 = columns (sum across the rows)
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [117]:
# 1 rows (sum across columns)
arr_2d.sum(axis=1)

array([10, 26, 42])